Repository opensource-community-Team-6/computer-science-curriculum, pull requests merged in 2020-09, with the labels that each got.

#10 [#9] refactor: 사용하지 않는 로드맵 제거
  src/data.js
  src/data/algorithms.js
  src/data/architecture-and-paradigmes.js
  src/data/build-tools.js
  src/data/computer_science.js
  src/data/databases.js
  src/data/design-and-ux.js
  src/data/frameworks-and-libraries.js
  src/data/information_communication.js
  src/data/modern.js
  src/data/pwa.js
  src/data/software.js
  src/data/team-collaboration.js
  src/data/testing.js
Labels: 리팩토링

#14 [#11] feature: 소프트웨어학과 1학년 이미지 적용
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/데이터베이스시스템.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/미래설계준비.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/미래설계탐색.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/빅데이터시스템설계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/산학프로젝트.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/알고리즘.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/오픈소스소프트웨어이해와실습.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/이산수학.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/자료구조.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/창의공학설계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/캡스톤-디자인-I.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/캡스톤-디자인-II.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/컴퓨터시스템개론.svg
Labels: 기능추가

#19 [#18] feat: 우석대학교 이미지 삽입
  assets/우석대학교-컴퓨터공학과-커리큘럼/1학년/비주얼프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/1학년/컴퓨터공학개론.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/1학년/프로그래밍언어1.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/1학년/프로그래밍언어2.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/논리회로.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/디지털콘텐츠-공학.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/리눅스-시스템.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/웹-프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/웹콘텐츠-제작.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/윈도우즈-프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/자료구조.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/자바프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/컴퓨터구조.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/프로그래밍어론.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/2학년/프로그래밍연습.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/XML-프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/그래픽스-프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/데이터베이스-프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/데이터베이스.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/데이터통신.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/마이크로프로세서.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/모바일-프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/소프트웨어공학.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/알고리즘.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/운영체제.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/컴퓨터-그래픽스.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/컴퓨터-네트워크.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/병렬-프로그래밍.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/소프트웨어-프로젝트(캡스톤디자인).svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/영상처리.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/인공지능.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/임베디드시스템1.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/임베디드시스템2.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/정보보안.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/졸업-프로젝트(캡스톤디자인).svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/4학년/현장실습.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/교직이수/정보,컴퓨터-교과-논리-및-논술.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/교직이수/정보,컴퓨터-교과교육론.svg
  assets/우석대학교-컴퓨터공학과-커리큘럼/교직이수/정보,컴퓨터-교과교재-연구-및-지도법.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/미래설계준비.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/미래설계탐색.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/빅데이터시스템설계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/산학프로젝트.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/오픈소스소프트웨어이해와실습.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/이산수학.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/창의공학설계.svg
Labels: 기능추가

#20 #18 폴더 추가
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/데이터베이스시스템.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/미래설계준비.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/미래설계탐색.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/빅데이터시스템설계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/산학프로젝트.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/알고리즘.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/오픈소스소프트웨어이해와실습.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/이산수학.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/자료구조.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/창의공학설계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/캡스톤-디자인-i.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/캡스톤-디자인-ii.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/1학년/컴퓨터시스템개론.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/객체지향-프로그래밍.svg
  src/data/computer_science.js
Labels: 기능수정

#23 [#22] fix: 누락 이미지 및 내용 수정
  assets/우석대학교-컴퓨터공학과-커리큘럼/3학년/xml프로그래밍.svg
  src/data/computer_science.js
Labels: 기능수정

#24 충북대학교 정보통신공학부 과목 이미지 추가
  assets/충북대학교-정보통신공학부-커리큘럼/1학년/전공입문세미나.svg
  assets/충북대학교-정보통신공학부-커리큘럼/1학년/종합설계1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/1학년/창의공학설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/C++언어.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/공학수학1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/공학수학2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/디지털공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/미래설계1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/미래설계2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/임베디드소프트웨어실습.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/전자기학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/전자회로1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/정보보호개론.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/정보통신개론.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/종합설계1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/종합설계2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/컴퓨터네트워크.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/확률및통계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/회로실험1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/회로실험2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/회로이론1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/회로이론2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/객체지향프로그래밍.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/기술작문및발표.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/데이터베이스시스템설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/데이터통신설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/디지털신호처리설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/디지털통신.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/모바일프로그래밍및실습.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/미래설계3.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/신호및시스템.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/안테나설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/영상처리.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/운영체제.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/인터넷통신설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/자료구조.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/전자회로1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/전자회로2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/정보통신실험.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/종합설계1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/종합설계2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/초고주파공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/통신공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/공업교육론.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/공업논리및논술.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/광통신.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/멀티미디어정보처리및실습.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/무선통신망공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/산학초청세미나1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/산학초청세미나2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/이동통신공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/전파광파소자.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/정보및부호이론.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/정보응용실험.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/종합설계2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/종합설계3.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/초고속통신망기초.svg
Labels: 기능추가

#26 [#25] fix: 이미지 파일명 수정
  src/data/information_communication.js
Labels: 버그

#27 [#25] fix: 누락 이미지 파일명 및 코드 수정
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/cpp언어.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/공학수학2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/전자회로1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/기술작문및발표.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/데이터통신설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/디지털신호처리설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/디지털통신.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/미래설계3.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/신호및시스템.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/안테나설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/영상처리.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/인터넷통신설계.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/전자회로1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/전자회로2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/정보통신실험.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/초고주파공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/광통신.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/멀티미디어정보처리및실습.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/무선통신망공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/산학초청세미나1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/산학초청세미나2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/이동통신공학.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/전파광파소자.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/정보및부호이론.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/정보응용실험.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/종합설계3.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/초고속통신망기초.svg
  src/data/information_communication.js
Labels: 버그

#28 [#11] feat: 소프트웨어학과 과목별 이미지
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/객체지향설계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/미래설계구현.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/선형대수학.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/소프트웨어공학.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/소프트웨어실전영어.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/시스템프로그래밍.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/오픈소스-기초프로젝트.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/오픈소스개발프로젝트.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/운영체제.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/창업탐색.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/컴퓨터구조.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/컴퓨터그래픽스.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/펌웨어프로그래밍.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/프로그래밍언어론.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/2학년/확률및통계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/오픈소스-웹소프트웨어.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/오픈소스전문프로젝트.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/인공지능.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/정보보호.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/창업-설계.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/창업기획.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/컴파일러.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/3학년/컴퓨터네트워크.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/기계학습.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/빅데이터분석시각화.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/실무프로젝트-i.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/실무프로젝트-iii.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/영상처리.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/인턴십-i.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/인턴십-ii.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/인턴십-iii.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/인턴십-iv.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/인턴십.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/임베디드시스템.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/자연어-처리.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/정보검색.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/창업산학세미나-i.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/창업산학세미나-ii.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/창업파일럿프로젝트.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/컴퓨터교육론.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/컴퓨터교재연구-및-지도법.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/컴퓨터논리-및-논술.svg
  assets/충북대학교-소프트웨어학과-커리큘럼/4학년/클라우드컴퓨팅.svg
  src/data/software.js
Labels: 기능수정, 기능추가

#31 [#30] modify: 선수과목 중복 제거
  assets/충북대학교-정보통신공학부-커리큘럼/1학년/미래설계1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/미래설계3.svg
  assets/충북대학교-정보통신공학부-커리큘럼/2학년/종합설계1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/전자회로1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/종합설계1.svg
  assets/충북대학교-정보통신공학부-커리큘럼/3학년/종합설계2.svg
  assets/충북대학교-정보통신공학부-커리큘럼/4학년/종합설계2.svg
  src/data/information_communication.js
Labels: 기능수정

#35 [#29, #34] feat: 전공필수 표시, 학점 표시
  src/molecules/skill.js
Labels: 기능추가

#37 [#36] feat: 소프트웨어학과 전공필수, 학점 표시
  src/data/software.js
Labels: 기능추가

#38 [#33] feat : 제목 링크 달기
  src/data/computer_science.js
  src/molecules/collection.js
Labels: 기능추가

#40 [#39] feat: 전공필수, 학점표시 및 교과구조 수정, 교직이수 추가
  src/data/computer_science.js
  src/molecules/skill.js
Labels: 기능추가

#43 [#42] 헤더 수정
  src/app.js
Labels: 기능수정, 기능추가

#47 [#46] 큰 제목 옆에 학교 로고 넣기
  assets/logo/우석대학교.png
  assets/logo/충북대학교.png
  src/data/computer_science.js
  src/data/information_communication.js
  src/data/software.js
  src/molecules/collection.js
Labels: 기능추가

#49 [#48] feat : 학과 소개 추가 및 제목 링크 양식 수정
  assets/logo/홈페이지.png
  src/molecules/collection.js
  src/util/open-help.js
Labels: 기능추가, 리팩토링

#51 [#50] feat: 정보통신공학부 전공필수, 학점 표시
  src/data/information_communication.js
Labels: 기능추가

#53 [#52] fix: 전공필수 수정
  src/data/computer_science.js
Labels: 기능수정

#54 [#32] feat: SW융합전공 EASY코스 커리큘럼 추가
  assets/SW융합전공-EASY코스-커리큘럼/1학기/iot-기술과-프로그래밍.svg
  assets/SW융합전공-EASY코스-커리큘럼/1학기/인공지능과-기계학습.svg
  assets/SW융합전공-EASY코스-커리큘럼/1학기/정보기술의-이해.svg
  assets/SW융합전공-EASY코스-커리큘럼/1학기/파이썬-프로그래밍.svg
  assets/SW융합전공-EASY코스-커리큘럼/2학기/모바일-프로그래밍.svg
  assets/SW융합전공-EASY코스-커리큘럼/2학기/운영체제의-이해.svg
  assets/SW융합전공-EASY코스-커리큘럼/2학기/웹-응용-프로그래밍.svg
  assets/SW융합전공-EASY코스-커리큘럼/2학기/자료구조와-문제해결.svg
  assets/SW융합전공-EASY코스-커리큘럼/2학기/자바프로그래밍.svg
  q
  src/data.js
  src/data/easy_course.js
  src/molecules/collection.js
Labels: 기능추가

#56 [#55] fix: SW융합전공 EASY코스 대문자를 소문자로 변경
  src/data/easy_course.js
Labels: 버그

#57 [#55] fix: 폴더명 대문자를 소문자로 변경
  assets/sw융합전공-easy코스-커리큘럼/1학기/iot-기술과-프로그래밍.svg
  assets/sw융합전공-easy코스-커리큘럼/1학기/인공지능과-기계학습.svg
  assets/sw융합전공-easy코스-커리큘럼/1학기/정보기술의-이해.svg
  assets/sw융합전공-easy코스-커리큘럼/1학기/파이썬-프로그래밍.svg
  assets/sw융합전공-easy코스-커리큘럼/2학기/모바일-프로그래밍.svg
  assets/sw융합전공-easy코스-커리큘럼/2학기/운영체제의-이해.svg
  assets/sw융합전공-easy코스-커리큘럼/2학기/웹-응용-프로그래밍.svg
  assets/sw융합전공-easy코스-커리큘럼/2학기/자료구조와-문제해결.svg
  assets/sw융합전공-easy코스-커리큘럼/2학기/자바프로그래밍.svg
Labels: 버그

#59 [#58] feat: 학과소개 추가 및 더미 파일 삭제
  assets/logo/sw중심대학사업단.png
  q
  src/util/open-help.js
Labels: 기능수정, 기능추가

#61 [#60] modify: sw융합전공 easy코스 이미지 변경
  src/data/easy_course.js
Labels: 기능수정
